config/routes.rb
Rails.application.routes.draw do
  namespace :api  do
    namespace :v1 do
      resources :inventory_items, only: [:show]
    end
  end
  get '/sessions/login' => 'sessions#new', as: 'login'
  delete '/sessions/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/:provider/create_session' => 'sessions#create'

  root to: 'inventory_items#index'

  resources :inventory_items, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :removals, only: [:new, :create, :show] do
    post '/undo' => 'removals#undo', as: 'undo'
  end

  resources :products, only: [:create, :new, :index]

  resources :users, only: [:show, :edit, :update]
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  resourcify
  validates :date_packaged, presence: true
  validates :packaging_run_id, presence: true

  belongs_to :product
  belongs_to :packaging_run
  has_many :inventory_item_amounts, dependent: :destroy
  has_many :amounts, through: :inventory_item_amounts
  has_many :removals, dependent: :destroy

  def create_new_removal(params, user_id)
    removal = self.removals.new(user_id: user_id,
                                reason: params[:reason],
                                description: params[:description])
    measurements = set_measurements(params)
    if removal.valid? && valid_removal_amounts?(measurements)
      removal.save
      measurements.each do |measurement, quantity|
        if quantity > 0
          removal.removal_amounts.create( amount: Amount.find_by(measurement: measurement),
                                          quantity: quantity)
          update_iia(measurement, quantity)
        end
      end
      removal
    else
      false
    end
  end

  def undo_removal_creation(removal_id)
    removal = Removal.find(removal_id)
    removal.removal_amounts.each do |ra|
      iia = self.inventory_item_amounts.find_by(amount_id: ra.amount_id)
      iia.quantity += ra.quantity
      iia.save!
      ra.delete
    end
    removal.delete
  end

  def save_new_packaging_run(**params)
    params[:quantities] ||= ['']
    empty_quantities = params[:quantities].any? {|a| a.empty?}
    if !empty_quantities && self.save
      params[:amounts].each_with_index do |amount, i|
        inventory_item_amount = self.inventory_item_amounts.find_or_create_by(amount_id: amount)
        inventory_item_amount.quantity = inventory_item_amount.quantity.to_i + params[:quantities][i].to_i
        inventory_item_amount.save
      end
    else
      self.valid?
      self.errors.add(:base, "Quantity can't be blank") if empty_quantities
      false
    end
  end

  def update_all(params)
    params[:quantity] ||= ['']
    empty_quantities = params[:quantity].any? {|a| a.empty?}
    self.product_id = params[:inventory_item][:product_id]
    self.packaging_run.number = params['Packaging Run ID']
    self.date_packaged = params[:inventory_item][:date_packaged]
    if self.packaging_run.valid? && self.valid? && !empty_quantities
      clear_quantities(params[:amount])
      params[:amount].each_with_index do |amount, i|
        inventory_item_amount = self.inventory_item_amounts.find_or_create_by(amount_id: amount)
        inventory_item_amount.quantity = inventory_item_amount.quantity.to_i + params[:quantity][i].to_i
        inventory_item_amount.save
      end
      self.packaging_run.save
      self.save
    else
      self.errors.add(:base, "Quantity can't be blank") if empty_quantities
      self.errors.add(:base, "Packaging Run ID already taken") unless self.packaging_run.valid?
      false
    end
  end

  def quantity_for(amount_id)
    query = generate_query :measurement_amounts, inventory_item_id: self.id
    @measurement_amounts ||=  InventoryItem.find_by_sql(query)
    @measurement_amounts = convert_to_hash unless @measurement_amounts.is_a? Hash
    @measurement_amounts[amount_id.to_i].to_i
  end

  def on_hold?
    packaging_run.on_hold
  end

  def delete_all
    self.packaging_run.delete
    self.delete
  end

  def available_amounts_and_removals(removal_id)
    query = generate_query :quantity_removal, removal_id: removal_id, inventory_item_id: self.id
    InventoryItem.find_by_sql(query)
  end

  def self.group_by_index_display
    query = self.new.generate_query :index_display
    self.find_by_sql(query)
  end

  private

  def clear_quantities(amounts)
    amounts.each do |amount|
      if iia = self.inventory_item_amounts.find_by(amount_id: amount)
        iia.quantity = 0
        iia.save
      end
    end
  end

  def set_measurements(params)
    measurements = Amount.pluck(:measurement)
    params.keys.reduce({}) do |result, param|
      result[param] = params[param].to_i if measurements.include?(param)
      result
    end
  end

  def valid_removal_amounts?(measurements)
    if measurements.values.all? {|a| a.zero?}
      self.errors.add(:base, "No amounts marked to be removed")
      return false
    end
    measurements.each do |measurement, quantity|
      quantity_limits = self.inventory_item_amounts
                            .includes(:amount)
                            .find_by(amounts: {measurement: measurement})
                            .quantity
      if quantity > quantity_limits
        self.errors.add(:base, "Quantity can't be larger than amount in packaging run")
        return false
      elsif quantity < 0
        self.errors.add(:base, "Quantity can't be less than zero")
        return false
      end
    end
    true
  end

  def update_iia(measurement, quantity)
    iia = self.inventory_item_amounts
              .includes(:amount)
              .find_by(amounts: {measurement: measurement})
    difference = iia.quantity - quantity
    iia.update(quantity: difference)
  end

  def convert_to_hash
    @measurement_amounts.reduce({}) do |result, data|
      result[data.amount_id] = data.quantity
      result
    end
  end
end

app/controllers/api/v1/inventory_items_controller.rb
class Api::V1::InventoryItemsController < ApplicationController
  def show
    inventory_item = PackagingRun.find_associated_inv_item(params[:id])
    amounts = inventory_item.inventory_item_amounts.reduce([]) do |result, iia|
      result << [iia.amount.measurement, iia.quantity]
    end
    render json: {
      id: inventory_item.id,
      product: inventory_item.product.name,
      amounts: amounts
    }
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :authorize_user # will replace with CanCanCan
  load_and_authorize_resource param_method: :item_params

  def index
    flash.clear
    flash[:success] = 'Removal Successfully Created' if params[:success]
    @inventory_items = InventoryItem.group_by_index_display
    @amounts = Amount.pluck(:id, :measurement)
  end

  def new
    @inventory_item = InventoryItem.new
  end

  def create
    @inventory_item = InventoryItem.new(product_id: item_params[:product_id],
                                        packaging_run: PackagingRun.create(number: params["Packaging Run ID"]),
                                        date_packaged: item_params[:date_packaged])
    if @inventory_item.save_new_packaging_run(amounts: params[:amount], quantities: params[:quantity])
      redirect_to inventory_items_path
      flash[:success] = 'Item Successfully Added to Inventory'
    else
      flash.now[:danger] = @inventory_item.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    inventory_item = InventoryItem.find(params[:id])
    inventory_item.delete_all
    flash[:success] = 'Item Permanently Deleted from Database'
    redirect_to inventory_items_path
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  def update
    @inventory_item = InventoryItem.find(params[:id])
    if @inventory_item.update_all(params)
      redirect_to inventory_items_path
      flash[:success] = 'Item Successfully Updated'
    else
      flash.now[:danger] = @inventory_item.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def item_params
    params.require(:inventory_item).permit(:product_id, :date_packaged, :amounts)
  end
end

@inventory_items = InventoryItem.joins(:packaging_run)
                                .merge(PackagingRun.order(on_hold: :asc))
                                .order(id: :desc)

app/views/inventory_items/_amount.html.erb
<div class='amountForm'>
  <%= label_tag 'Amount' %>
  <%= select_tag 'amount[]', options_for_select(Amount.all.collect{ |a| [a.measurement, a.id]}, [measurement]) %>
  <%= label_tag 'Qty' %>
  <%= number_field_tag 'quantity[]', quantity || '0', min: 0 %>
  <a href='#' onclick='removeAmount(event, $(this))' class='remove-amount'> x </a> <br/>
</div>

app/views/inventory_items/edit.html.erb
<div class="container">
  <h1>Edit Item in Inventory</h1>

  <%= form_for @inventory_item do |f| %>
    <div class='fields'>
      <%= f.label :packaging_run, 'Packaging Run ID' %>
      <%= f.number_field :packaging_run, name: 'Packaging Run ID', class: 'form-group', min: 0, value: @inventory_item.packaging_run.number %> <br/>

      <%= f.label :product_id, 'Product' %>
      <%= f.collection_select(:product_id, Product.all, :id, :name, {value: @inventory_item.product.name}) %> <br/>

      <%= f.label :date_packaged, 'Date Packaged' %>
      <%= f.date_field :date_packaged %> <br/>

      <div id='amounts'>
        <% @inventory_item.inventory_item_amounts.each do |iia| %>
          <%= render partial: 'amount', locals: {measurement: iia.amount.id, quantity: iia.quantity} %>
        <% end %>
      </div>
      <a href='javascript:;' onclick='addAmount(event)' class='remove-amount'>Add Another Measurement</a><br/>
    </div>

    <div class='actions'>
      <%= f.submit 'Submit Changes' %>
    </div>
  <% end %>
</div>

<div style='display: none;' id='new_amount_form'>
  <%= render partial: 'amount', locals: {measurement: nil, quantity: nil} %>
</div>

app/views/inventory_items/index.html.erb
<div class="container">
  <h1 class="title">Current Inventory</h1>

  <% @inventory_items.each do |item| %>
    <div class="ui container" id="inventory-item">
      <% if item.packaging_run.on_hold %>
        <div class="ui_box on_hold">
      <% else %>
        <div class="ui_box">
      <% end %>
        <div class="ui_box__inner">
          <div class="stat_right">
            <% @amounts.each do |amount| %>
              <div class="amount-box">
                <span><%= amount.last %></span>
                <p><%= item.quantity_for(amount.first) %></p>
              </div>
            <% end %>
          </div>

          <div class="ui_box_buttons">
            <% unless item.packaging_run.on_hold %>
              <%= link_to 'New Removal', new_removal_path(prid: item.packaging_run.number), class: 'btn btn-primary active', role: 'button' %><br/>
            <% end %>
            <%= link_to 'Edit', edit_inventory_item_path(item.id), class: 'btn btn-warning active', role: 'button' %><br/>

            <% if can? :destroy, item %>
              <%= link_to 'Delete', inventory_item_path(item.id), method: :delete, data: {confirm: 'Permanently delete this record?'}, class: 'btn btn-danger active', role: 'button' %><br/>
            <% end %>
          </div>

          <ul>
            <li>On Hold:</li>
            <p><%= item.packaging_run.on_hold ? 'True' : 'False' %></p>
            <li>PRID:</li>
            <p><%= item.packaging_run.number %></p>
            <li>Brand:</li>
            <p><%= item.product.name %></p>
            <li>Date Packaged:</li>
            <p><%= item.date_packaged %></p>
          </ul>
        </div>
        <div class="drop">
          <p>View timeline</p>
          <div class="arrow"></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/inventory_items/new.html.erb
<div class="container">
  <h1>Add New Item to Inventory</h1>

  <%= form_for @inventory_item do |f| %>
    <div class='fields'>
      <%= f.label :packaging_run, 'Packaging Run ID' %>
      <%= f.number_field :packaging_run, name: 'Packaging Run ID', class: 'form-group', min: 0%> <br/>

      <%= f.label :product_id, 'Product' %>
      <%= f.collection_select(:product_id, Product.all, :id, :name) %> <br/>

      <%= f.label :date_packaged, 'Date Packaged' %>
      <%= f.date_field :date_packaged %> <br/>

      <div id='amounts'>
        <%= render partial: 'amount', locals: {measurement: nil, quantity: nil} %>
      </div>
      <a href='javascript:;' onclick='addAmount(event)' class='remove-amount'>Add Another Measurement</a><br/>
    </div>

    <div class='actions'>
      <%= f.submit 'Add Inventory' %>
    </div>
  <% end %>
</div>

<div style='display: none;' id='new_amount_form'>
  <%= render partial: 'amount', locals: {measurement: nil, quantity: nil} %>
</div>