config/routes.rb
Rails.application.routes.draw do
  namespace :api  do
    namespace :v1 do
      resources :inventory_items, only: [:show]
    end
  end
  get '/sessions/login' => 'sessions#new', as: 'login'
  delete '/sessions/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/:provider/create_session' => 'sessions#create'

  root to: 'inventory_items#index'

  resources :inventory_items, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :removals, only: [:new, :create, :show] do
    post '/undo' => 'removals#undo', as: 'undo'
  end

  resources :products, only: [:create, :new, :index]

  resources :users, only: [:show, :edit, :update]
end

app/views/shared/_flash_alerts.html.erb
<center><% flash.each do |type, message| %>
  <%= content_tag :div, message.html_safe, class: "alert alert-#{type}" %>
<% end %></center>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'vár', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
      <% if logged_in? %>
        <span class="navbar-text" id="signed-in-text">
          Logged in as <%= current_user.name %>
        </span>
        <li class="nav-item"><%= link_to 'View Current Products', products_path, class: "nav-link" %></li>
        <% if can? :create, Product %>
          <li class="nav-item" id="new-product-link"><%= link_to '+ Add New Product', new_product_path, class: "nav-link" %></li>
        <% end %>
          <li class="nav-item"><%= link_to 'View Current Inventory', inventory_items_path, class: "nav-link" %></li>
          <li class="nav-item" id="new-inventory-link"><%= link_to '+ Add New Inventory', new_inventory_item_path, class: "nav-link" %></li>
          <li class="nav-item" id="remove-inventory-link"><%= link_to '- Record Inventory Removal', new_removal_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Profile Settings', user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Login', login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>