config/routes.rb
Rails.application.routes.draw do
  namespace :api  do
    namespace :v1 do
      resources :inventory_items, only: [:show]
    end
  end
  get '/sessions/login' => 'sessions#new', as: 'login'
  delete '/sessions/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/:provider/create_session' => 'sessions#create'

  root to: 'inventory_items#index'

  resources :inventory_items, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :removals, only: [:new, :create, :show] do
    post '/undo' => 'removals#undo', as: 'undo'
  end

  resources :products, only: [:create, :new, :index]

  resources :users, only: [:show, :edit, :update]
end

app/models/removal.rb
class Removal < ApplicationRecord
  resourcify
  validates :reason, presence: true

  belongs_to :user
  belongs_to :inventory_item
  has_many :removal_amounts, dependent: :destroy
  has_many :amounts, through: :removal_amounts

  def delete_all
    self.removal_amounts.each { |ra| ra.delete }
    self.delete
  end
end

app/controllers/removals_controller.rb
class RemovalsController < ApplicationController
  before_action :authorize_user # will replace with CanCanCan
  before_action :confirm_removal_authorized, only: [:show, :undo]
  skip_before_action :reset_undo_status, only: [:show, :undo]
  load_and_authorize_resource

  def new
    @prids =  if PackagingRun.find_by(number: params[:prid])
                params[:prid]
              else
                PackagingRun.where(on_hold: false).order(number: :desc).pluck(:number)
              end
    @reasons = %w{Order Taproom Loss\ &\ Destruction}
  end

  def create
    inventory_item = PackagingRun.find_associated_inv_item(params[:packaging_run])
    if removal = inventory_item.create_new_removal(item_params, current_user.id)
      session[:confirm_removal] = 'true'
      redirect_to removal_path(removal)
    else
      flash[:danger] = inventory_item.errors.full_messages.join(', ')
      redirect_to new_removal_path
    end
  end

  def show
    @removal = Removal.find(params[:id])
    @inventory_item = @removal.inventory_item
    flash[:info] = "Confirm Removal for ID: #{@inventory_item.packaging_run.number}"
  end

  def undo
    flash[:danger] = 'Removal Deleted and Changes Were Not Saved'
    removal = Removal.find(params[:removal_id])
    inventory_item = removal.inventory_item
    inventory_item.undo_removal_creation(removal.id)
    session[:confirm_removal] = nil
    redirect_to new_removal_path
  end

  private
  def item_params
    desired_params = [:reason, :description] + Amount.pluck(:measurement)
    params.permit(desired_params)
  end

  def confirm_removal_authorized
    raise ActionController::RoutingError.new('Not Found') unless session[:confirm_removal]
  end
end

app/views/removals/new.html.erb
<div class="container">
  <div class="removals new">
    <h1>Add New Removal to Inventory</h1>

    <%= form_tag '/removals' %>
      <%= label_tag 'packaging_run', 'Packaging Run ID' %>
      <% if @prids.is_a? Array %>
        <%= select_tag 'packaging_run', options_for_select(@prids), id: 'prid-removal' %> <br/>
      <% else %>
        <%= hidden_field_tag 'packaging_run', @prids, id: 'prid-removal' %>
        <strong><%= @prids %></strong><br/>
      <% end %>

      <%= label_tag 'reason' %>
      <%= select_tag 'reason', options_for_select(@reasons), id: 'reason-removal' %> <br/>

      <div id='reason-description' style='display: none;'>
        <%= text_area_tag 'description', nil, placeholder: 'Reason For Loss', size: '45x5' %>
      </div>

      <div id='amounts-removal'></div>

      <%= submit_tag 'Add Removal' %>
  </div>
</div>

app/views/removals/show.html.erb
<div class="container">
  <center>
    <h1 class='title'>Confirm New Removal</h1>
    <h4>Prackaging Run ID <%= @inventory_item.packaging_run.number %></h4>
    <p>Removing product <%= @inventory_item.product.name %></p>
    <table class='table table-sm table-striped'>
      <tr>
        <th>Measurement</th>
        <th>Quantity to be Removed</th>
        <th>Remaining Quantity</th>
      </tr>
      <% @inventory_item.available_amounts_and_removals(@removal.id).each do |iia| %>
        <tr>
          <td><%= iia.measurement %></td>
          <td><%= iia.removal %></td>
          <td><%= iia.quantity %></td>
        </tr>
      <% end %>
    </table>
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <%= link_to 'Confirm', root_path(success: 'removal'), data: {confirm: 'You will not be able to edit or undo this removal after confirming. Continue?'}, class: 'btn btn-primary active', role: 'button' %>
      </div>
      <div class="col">
        <%= link_to 'Undo', removal_undo_path(@removal.id), method: :post, data: {confirm: 'Undo changes and permanently delete this removal?'}, class: 'btn btn-warning active', role: 'button' %>
      </div>
      <div class="col"></div>
    </div>
  </center>
</div>